name: Mike Harrison Photography
url: http://mikejharrison.github.io
date_format: '%B %d, %Y'

# Owner configuration
# name and email are required (change code to remove these)
# (leave the rest blank to disable the corresponding sharing button)
owner:
    name: Mike Harrison
    email: mikehimages@gmail.com
    github:
    twitter:
    linkedin:
    facebook:
    google_plus:
    youtube:

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname:

markdown: kramdown
highlighter: rouge # or pygments or null
paginate: 5
exclude: ["node_modules", "gulpfile.js", "package.json", "readme.md"]
excerpt_separator: <!--more-->
gems: [jekyll-paginate]
