name: Mike Harrison Photography
markdown: redcarpet
highlighter: rouge # or pygments or null
paginate: 5
exclude: ["node_modules", "gulpfile.js", "package.json"]
excerpt_separator: <!--more-->
gems: [jekyll-paginate]
